[default]
width = 16.0
height = 1.5
offset_x = 0.0
offset_y = 10.0
background_padding = 0.25

[colors]
background = [0.4, 0.4, 0.4, 1.0]
current_hp = [1.0, 0.0, 0.0, 1.0]
delayed_damage = [0.8, 0.8, 0.2, 1.0]
delayed_heal = [1.0, 0.7, 0.8, 1.0]
transparent = [0.0, 0.0, 0.0, 0.0]

[timing]
delay_before_animation = 0.5
animation_duration = 0.5
visibility_timeout = 3.0
fade_duration = 0.5