[settings]
active_preset = "all"

[default]
tags = ["default"]

[[preset]]
name = "all"
tags = ["default", "camera", "red_slime"]

[[preset]]
name = "camera_only"
tags = ["camera"]

[[preset]]
name = "slime_only"
tags = ["red_slime"]
